In [1]:
def Divisible(numberList):
    print("Given list is ", numberList)
    print("Divisible of 5 in a list")
    for num in numberList:
        if (num % 5 == 0):
            print(num)

numList = [10, 20, 33, 46, 55]
Divisible(numList)

Given list is  [10, 20, 33, 46, 55]
Divisible of 5 in a list
10
20
55


In [15]:
#import numpy
import numpy as np
#make a list with np 
list = np.array([10, 20, 33, 46, 55]) 

print('Divisible of 5 in a list')
print(list)
#Then i print in an array the results of multiply by 5
list[list%5 == 0] 


Divisible of 5 in a list
[10 20 33 46 55]


array([10, 20, 55])

In [16]:
def mergeList(listOne, listTwo):
    print("First List ", listOne)
    print("Second List ", listTwo)
    thirdList = []
    
    for num in listOne:
        if (num % 2 != 0):
            thirdList.append(num)
    for num in listTwo:
        if (num % 2 == 0):
            thirdList.append(num)
    return thirdList

listOne = [10, 20, 23, 11, 17]
listTwo = [13, 43, 24, 36, 12]

print("result List is", mergeList(listOne, listTwo))

First List  [10, 20, 23, 11, 17]
Second List  [13, 43, 24, 36, 12]
result List is [23, 11, 17, 24, 36, 12]


In [25]:
#import the librarie numpy
import numpy as np
#define the list
listone= np.array([10, 20, 23, 11, 17])
listtwo = np.array([13, 43, 24, 36, 12])
#make the result of odd and even numer
a =listone[listone%2 != 0]
b = listtwo[listtwo%2 == 0]
#combine in an array
np.concatenate([a, b], axis = 0)



array([23, 11, 17, 24, 36, 12])